version: '3'

services:
  esc-guard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: esc-guard
    volumes:
      - ./:/process
      - /process/node_modules
    ports:
      - "3334:3333"
    env_file:
      - .env
    networks:
      - esc-network
    restart: on-failure

networks:
  esc-network:
    external:
      name: esc-network
