apiVersion: v1
kind: Service
metadata:
  name: esc-guard
  namespace: easycontabil
spec:
  ports:
    - port: 80
      # name: rest
      protocol: TCP
      targetPort: http
      # - port: 50051
      #   name: grpc
      #   protocol: TCP
      #   targetPort: 50051
  selector:
    run: esc-guard
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esc-guard
  namespace: easycontabil
spec:
  selector:
    matchLabels:
      run: esc-guard
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        run: esc-guard
    spec:
      nodeSelector:
        group: apps-public-vpc
      tolerations:
        - key: "group"
          operator: "Equal"
          value: "apps-public-vpc"
          effect: "NoSchedule"
        - key: "group"
          operator: "Equal"
          value: "apps-public-vpc"
          effect: "NoExecute"
      containers:
        - image: jlenon7/esc-guard:1.1.2
          imagePullPolicy: IfNotPresent
          name: esc-guard
          envFrom:
            - configMapRef:
                name: esc-guard
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
          resources:
            limits:
              memory: 700Mi
            requests:
              memory: 700Mi
          readinessProbe:
            httpGet:
              path: /grd/welcome
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /grd/welcome
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 20
      imagePullSecrets:
        - name: dockerhub
